config/routes.rb
Rails.application.routes.draw do
  get 'meals/grouped_ratings', to: 'meals#ratings'
  resources :reviews
  resources :meals do 
    resources :reviews, only: [:new, :index]
  end

  resources :restaurants
  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#welcome'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :restaurant
    has_many :reviews, through: :users
    has_many :users, through: :reviews

    accepts_nested_attributes_for :restaurant

    validates :name, presence: true
    validates :description, presence: true

    scope :grouped_ratings, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}

    def self.alphabetical_order
        order(:name)
    end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :meals
    has_many :reviews, through: :meals
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :meal
  has_many :restaurants, through: :meals

  validates :title, presence: true
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :reviews
         has_many :reviewed_meals, through: :reviews, source: :meal

         has_many :meals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
    end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

    def index
        @meals = Meal.all
    end

    def show
        @meal = Meal.find(params[:id])
        @restaurant = @meal.restaurant
    end

    def new
        @meal = Meal.new
        @meal.build_restaurant
    end

    def create
        @meal = Meal.new(meal_params)
        if @meal.save
            redirect_to meals_path
        else
            @meal.build_restaurant
            render :new
        end
    end

    def edit
        @meal = Meal.find(params[:id])
    end

    def update
        @meal = Meal.find(params[:id])
        @meal.update()
    end

    def ratings
        @meals = Meal.grouped_ratings
    end

    private

    def meal_params
        params.require(:meal).permit(:name, :description, :restaurant_id, restaurant_attributes: [:name, :description])
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    if @meal = Meal.find_by_id(params[:meal_id])
        @reviews = @meal.reviews.all
     else
        @reviews = Review.all
        end
  end

  def new
    if @meal = Meal.find_by_id(params[:meal_id])
        @review = @meal.reviews.build
     else
        @review = Review.new
        end
    end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
        redirect_to review_path(@review)
    else
        render :new
    end
end

    def show
        @review = Review.find_by_id(params[:id])
    end

  private

  def review_params
    params.require(:review).permit(:stars, :title, :content, :meal_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/welcome.html.erb
<h1>Hello world</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<ul>
    <li><%= link_to "Home", root_path %></li>
    <% if !user_signed_in? %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
    <% else %>
        <li><%= link_to "Add new meal", new_meal_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VeganReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<h1>Make a new meal</h1>

<%= render partial: 'layouts/errors', locals:{object: @meal}%>
<%= form_for(@meal) do |f| %>
   <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </div>

        <p>Select a Restaurant: </p>
        <div>
            <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name, include_blank: "Choose one" %>
        </div>

        <p>Create a new Restaurant: </p>
        <div>
            <%= f.fields_for :restaurant do |r| %>
                <%= r.label :name %>
                <%= r.text_field :name %><br>
                <% end %>
        </div><br>
    <%= f.submit %>
    <% end %>

app/views/meals/edit.html.erb
<%= render partial: 'form' %>

app/views/meals/index.html.erb
<h1>Index</h1>

<% @meals.each do |m| %>
    <h2><%= m.name %> - <%= m.restaurant.name %><br></h2>
    <%= m.description %>
    <% end %>

app/views/meals/new.html.erb
<%= render partial: 'form' %>

app/views/meals/ratings.html.erb
<h1>Welcome to your ratings</h1>

<% @meals.each do |m| %>
    <%= m.name %> - <%= m.description %><br>
    <%= m.reviews.each do |r| %>
        <%= r.title %><br>
        <%= r.stars %><br>
        <%= r.content %><br>
    <% end %>
    <%= link_to "Review this meal", new_meal_review_path(m) %>
<% end %>

app/views/meals/show.html.erb
<%= @meal.name %><br>
<%= @meal.description %>
<%= @meal.restaurant.name %>

app/views/reviews/index.html.erb
<% if @meal %>
    <h1>AView all the reviews for <%= @meal.name %></h1>
    <% else %>
    <h1>View all reviews </h1>
<% end %>

<% @reviews.each do |r| %>
    <h2><%= r.meal.name %></h2> 
    <h3><%= r.title %></h3>
    <%= r.stars %><br>
    <%= r.content %><br>
    <% end %>

app/views/reviews/new.html.erb
<%= render partial: 'layouts/errors', locals:{object: @review}%>

<% if @meal %>
    <h1>Add a review for <%= @meal.restaurant.name %> <%= @meal.name %></h1>
    <% else %>
    <h1>Add a review </h1>
<% end %>

<%= form_for(@review) do |f| %>
    <% if params[:meal_id] %>
    <%= f.hidden_field :meal_id %>
    <% else %>
        <div<
         <%= f.label :meal_id, "Select a meal" %>
         <%=  f.collection_select :meal_id, Meal.all, :id, :name, include_blank: true %>
        </div>
        <% end %>

   <div>
        <%= f.label :stars %>
        <%= f.number_field :stars, min:1, max:5 %>
    </div>

    <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
</div>

<%= f.submit %>

<% end %>

app/views/reviews/show.html.erb
<h1>Your review for <%= @review.meal.name %></h1>

<%= @review.title %><br>
<%= @review.stars %><br>
<%= @review.content %><br>